
// Add AmmoType translation
BULLET_PLAYER_338MAG = "XBowBolt"
BULLET_PLAYER_45ACP = "Pistol"
BULLET_PLAYER_50AE = "357"
BULLET_PLAYER_556MM = "SMG1"
BULLET_PLAYER_556MM_BOX = "SMG1"
BULLET_PLAYER_57MM = "Pistol"
BULLET_PLAYER_762MM = "SMG1"
BULLET_PLAYER_9MM = "Pistol"
BULLET_PLAYER_BUCKSHOT = "Buckshot"

