

--------CSS WEAPON ICONS

resource.AddFile( "materials/VGUI/entities/weapon_ak47.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_ak47_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_aug.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_aug_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_awp.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_awp_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_deagle.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_deagle_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_famas.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_famas_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_fiveseven.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_fiveseven_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_g3sg1.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_g3sg1_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_galil.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_galil_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_glock.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_glock_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_m3.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_m3_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_m4a1.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_m4a1_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_m249.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_m249_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_mac10.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_mac10_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_mp5.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_mp5navy_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_p90.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_p90_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_p228.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_p228_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_scout.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_scout_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_sg550.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_sg550_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_sg552.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_sg552_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_tmp.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_tmp_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_ump45.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_ump45_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_usp.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_usp_ryno.vtf" )
resource.AddFile( "materials/VGUI/entities/weapon_xm1014.vmt" )
resource.AddFile( "materials/VGUI/entities/weapon_xm1014_ryno.vtf" )


--------OTHER STUFF

resource.AddFile( "resource/fonts/Cstrike.ttf" )
resource.AddFile( "materials/weapons/scopes/scope.vmt" )
resource.AddFile( "materials/weapons/scopes/scope.vtf" )
