
// Add Default Language translation (saves adding it to the txt files)
language.Add( "Cstrike_WPNHUD_AK47", "CV-47" )
language.Add( "Cstrike_WPNHUD_Aug", "BULLPUP" )
language.Add( "Cstrike_WPNHUD_AWP", "MAGNUM SNIPER RIFLE" )
language.Add( "Cstrike_WPNHUD_DesertEagle", "NIGHT HAWK .50C" )
language.Add( "Cstrike_WPNHUD_Elites", ".40 DUAL ELITES" )
language.Add( "Cstrike_WPNHUD_Elite", ".40 SINGLE ELITE" )
language.Add( "Cstrike_WPNHUD_M4", "M4A1 BUSHMASTER" )
language.Add( "Cstrike_WPNHUD_SCARL", "SCAR-L" )
language.Add( "Cstrike_WPNHUD_Famas", "CLARION 5.56" )
language.Add( "Cstrike_WPNHUD_FiveSeven", "ES FIVE-SEVEN" )
language.Add( "Cstrike_WPNHUD_Flashbang", "FLASHBANG" )
language.Add( "Cstrike_WPNHUD_G3SG1", "D3/AU-1" )
language.Add( "Cstrike_WPNHUD_Galil", "IDF DEFENDER" )
language.Add( "Cstrike_WPNHUD_Glock18", "9X19MM SIDEARM" )
language.Add( "Cstrike_WPNHUD_HE_Grenade", "HE GRENADE" )
language.Add( "Cstrike_WPNHUD_Knife", "KNIFE" )
language.Add( "Cstrike_WPNHUD_M249", "M249" )
language.Add( "Cstrike_WPNHUD_m3", "LEONE 12 GAUGE SUPER" )
language.Add( "Cstrike_WPNHUD_M4A1", "MAVERICK M4A1 CARBINE" )
language.Add( "Cstrike_WPNHUD_M4A1RIS", "M4A1 RIS" )
language.Add( "Cstrike_WPNHUD_M4A1RISEOTECH", "M4A1 RIS (EOTECH)" )
language.Add( "Cstrike_WPNHUD_M4A1RISACOG", "M4A1 RIS (ACOG)" )
language.Add( "Cstrike_WPNHUD_M4A1RISREDDOT", "M4A1 RIS (RED DOT)" )
language.Add( "Cstrike_WPNHUD_M4A1RISCARRIER", "M4A1 RIS (CARRIER)" )
language.Add( "Cstrike_WPNHUD_MAC10", "INGRAM MAC-10" )
language.Add( "Cstrike_WPNHUD_MP5", "K&M SUB-MACHINE GUN" )
language.Add( "Cstrike_WPNHUD_P228", "228 COMPACT" )
language.Add( "Cstrike_WPNHUD_P90", "ES C90" )
language.Add( "Cstrike_WPNHUD_Scout", "SCHMIDT SCOUT" )
language.Add( "Cstrike_WPNHUD_SG550", "KRIEG 550 COMMANDO" )
language.Add( "Cstrike_WPNHUD_SG552", "KRIEG 552" )
language.Add( "Cstrike_WPNHUD_Smoke_Grenade", "SMOKE GRENADE" )
language.Add( "Cstrike_WPNHUD_Tmp", "SCHMIDT MACHINE PISTOL" )
language.Add( "Cstrike_WPNHUD_UMP45", "K&M UMP45" )
language.Add( "Cstrike_WPNHUD_USP45", "K&M .45 TACTICAL" )
language.Add( "Cstrike_WPNHUD_xm1014", "LEONE YG1265 AUTO SHOTGUN" )
language.Add( "Cstrike_WPNHUD_C4", "C4 EXPLOSIVE" )
language.Add( "Cstrike_WPNHUD_FNP45", "FNP .45" )
language.Add( "Cstrike_WPNHUD_FNP45_SIL", "FNP .45 (SILENCED)" )
